const booksData = [
    { id: 1, title: "The Time Machine", author: "H.G. Wells", category: "Sci-Fi", description: "A science fiction novel about time travel.", rating: 4.2 },
    { id: 2, title: "1984", author: "George Orwell", category: "Fiction", description: "Dystopian novel about a totalitarian regime.", rating: 4.8 },
    { id: 3, title: "Sapiens", author: "Yuval Noah Harari", category: "Non-Fiction", description: "A brief history of humankind.", rating: 4.7 },
    { id: 4, title: "Dune", author: "Frank Herbert", category: "Sci-Fi", description: "Epic science fiction story set on the desert planet Arrakis.", rating: 4.5 },
    { id: 5, title: "Pride and Prejudice", author: "Jane Austen", category: "Fiction", description: "Classic romance novel set in 19th-century England.", rating: 4.9 },
    { id: 6, title: "To Kill a Mockingbird", author: "Harper Lee", category: "Fiction", description: "A powerful tale of racial injustice in the American South.", rating: 4.8 },
    { id: 7, title: "The Great Gatsby", author: "F. Scott Fitzgerald", category: "Fiction", description: "A story of wealth and decadence in the Jazz Age.", rating: 4.6 },
    { id: 8, title: "Harry Potter and the Sorcerer’s Stone", author: "J.K. Rowling", category: "Fantasy", description: "A boy discovers he’s a wizard and attends a magical school.", rating: 4.7 },
    { id: 9, title: "The Catcher in the Rye", author: "J.D. Salinger", category: "Fiction", description: "A teenager’s thoughts and struggles in New York City.", rating: 4.3 },
    { id: 10, title: "The Hobbit", author: "J.R.R. Tolkien", category: "Fantasy", description: "A hobbit goes on an epic adventure to reclaim a treasure.", rating: 4.8 },
    { id: 11, title: "Moby-Dick", author: "Herman Melville", category: "Fiction", description: "The quest for vengeance against the white whale.", rating: 4.1 },
    { id: 12, title: "War and Peace", author: "Leo Tolstoy", category: "Historical Fiction", description: "An expansive tale set during the Napoleonic Wars.", rating: 4.6 },
    { id: 13, title: "The Odyssey", author: "Homer", category: "Classic", description: "An epic poem of Odysseus’ journey home.", rating: 4.4 },
    { id: 14, title: "Brave New World", author: "Aldous Huxley", category: "Fiction", description: "A dystopian society governed by technology and control.", rating: 4.7 },
    { id: 15, title: "The Alchemist", author: "Paulo Coelho", category: "Fiction", description: "A young shepherd’s journey to find his destiny.", rating: 4.7 },
    { id: 16, title: "Frankenstein", author: "Mary Shelley", category: "Sci-Fi", description: "A scientist creates life with unexpected consequences.", rating: 4.5 },
    { id: 17, title: "The Lord of the Rings", author: "J.R.R. Tolkien", category: "Fantasy", description: "A quest to destroy a powerful ring.", rating: 4.9 },
    { id: 18, title: "The Book Thief", author: "Markus Zusak", category: "Fiction", description: "A story of a girl in Nazi Germany who steals books.", rating: 4.8 },
    { id: 19, title: "The Road", author: "Cormac McCarthy", category: "Fiction", description: "A post-apocalyptic journey of survival.", rating: 4.3 },
    { id: 20, title: "Animal Farm", author: "George Orwell", category: "Fiction", description: "An allegorical novella about a rebellion of farm animals.", rating: 4.5 },
    { id: 21, title: "Gone with the Wind", author: "Margaret Mitchell", category: "Fiction", description: "A romantic story set during the American Civil War.", rating: 4.7 },
    { id: 22, title: "The Hitchhiker's Guide to the Galaxy", author: "Douglas Adams", category: "Sci-Fi", description: "A hilarious space adventure across the galaxy.", rating: 4.8 },
    { id: 23, title: "The Kite Runner", author: "Khaled Hosseini", category: "Fiction", description: "A moving tale of friendship and redemption in Afghanistan.", rating: 4.9 },
    { id: 24, title: "Crime and Punishment", author: "Fyodor Dostoevsky", category: "Fiction", description: "A psychological exploration of guilt and redemption.", rating: 4.6 },
    { id: 25, title: "The Secret", author: "Rhonda Byrne", category: "Self-Help", description: "Explores the concept of the law of attraction.", rating: 4.2 },
    { id: 26, title: "The Silent Patient", author: "Alex Michaelides", category: "Mystery", description: "A psychological thriller about a woman who refuses to speak.", rating: 4.4 },
    { id: 27, title: "A Song of Ice and Fire", author: "George R.R. Martin", category: "Fantasy", description: "An epic saga of power and politics in a medieval world.", rating: 4.8 },
    { id: 28, title: "The Art of War", author: "Sun Tzu", category: "Philosophy", description: "A classic treatise on strategy and warfare.", rating: 4.3 },
    { id: 29, title: "The Shining", author: "Stephen King", category: "Horror", description: "A chilling tale set in a haunted hotel.", rating: 4.5 },
    { id: 30, title: "The Girl on the Train", author: "Paula Hawkins", category: "Mystery", description: "A suspenseful story about an unreliable narrator.", rating: 4.1 },
    { id: 31, title: "The Power of Now", author: "Eckhart Tolle", category: "Self-Help", description: "A guide to spiritual awakening and living in the present.", rating: 4.6 },
    { id: 32, title: "The Hunger Games", author: "Suzanne Collins", category: "Fantasy", description: "A dystopian story of survival and rebellion.", rating: 4.7 },
    { id: 33, title: "The Handmaid's Tale", author: "Margaret Atwood", category: "Fiction", description: "A chilling tale set in a dystopian future.", rating: 4.6 },
    { id: 34, title: "Memoirs of a Geisha", author: "Arthur Golden", category: "Historical Fiction", description: "The story of a geisha's journey and struggles in Japan.", rating: 4.7 },
    { id: 35, title: "Life of Pi", author: "Yann Martel", category: "Fiction", description: "A boy survives on a lifeboat with a tiger.", rating: 4.4 },
    { id: 36, title: "The Maze Runner", author: "James Dashner", category: "Sci-Fi", description: "A group of teens face challenges in a mysterious maze.", rating: 4.2 },
    { id: 37, title: "The Picture of Dorian Gray", author: "Oscar Wilde", category: "Fiction", description: "A cautionary tale of vanity and morality.", rating: 4.6 },
    { id: 38, title: "A Thousand Splendid Suns", author: "Khaled Hosseini", category: "Fiction", description: "A powerful tale of love and hardship in Afghanistan.", rating: 4.9 },
    { id: 39, title: "Dracula", author: "Bram Stoker", category: "Horror", description: "A gothic classic about vampires and terror.", rating: 4.5 },
    { id: 40, title: "Percy Jackson and the Olympians", author: "Rick Riordan", category: "Fantasy", description: "A boy discovers he’s a demigod and embarks on adventures.", rating: 4.7 },
    { id: 41, title: "The Da Vinci Code", author: "Dan Brown", category: "Mystery", description: "A suspenseful tale involving art, history, and secrets.", rating: 4.4 },
    { id: 42, title: "The Fountainhead", author: "Ayn Rand", category: "Philosophy", description: "An exploration of individuality and architecture.", rating: 4.3 },
    { id: 43, title: "Wuthering Heights", author: "Emily Brontë", category: "Fiction", description: "A dark romantic tale set on the Yorkshire moors.", rating: 4.6 },
    { id: 44, title: "The Chronicles of Narnia", author: "C.S. Lewis", category: "Fantasy", description: "An adventurous tale of siblings in a magical land.", rating: 4.7 },
    { id: 45, title: "Don Quixote", author: "Miguel de Cervantes", category: "Classic", description: "The story of an eccentric knight and his adventures.", rating: 4.4 },
    { id: 46, title: "The Twilight Saga", author: "Stephenie Meyer", category: "Fantasy", description: "A love story between a vampire and a human.", rating: 4.2 },
    { id: 47, title: "The Giver", author: "Lois Lowry", category: "Fiction", description: "A dystopian tale of a boy discovering the truth about his world.", rating: 4.6 },
    { id: 48, title: "Atlas Shrugged", author: "Ayn Rand", category: "Philosophy", description: "An exploration of reason, capitalism, and individualism.", rating: 4.5 },
    { id: 49, title: "The Shadow of the Wind", author: "Carlos Ruiz Zafón", category: "Fiction", description: "A mystery set in Barcelona about books and secrets.", rating: 4.7 },
    { id: 50, title: "The Name of the Wind", author: "Patrick Rothfuss", category: "Fantasy", description: "The tale of a gifted young man’s rise and struggles.", rating: 4.8 },
];



export default booksData;